Exit if configuration file can't be read.
git-svn-id: http://lm-sensors.org/svn/lm-sensors/trunk@5667 7894878c-1315-0410-8ee3-d5d059ff63e0

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -54,6 +54,12 @@ declare -i pwmval
 
 function LoadConfig {
 	echo "Loading configuration from $1 ..."
+	if [ ! -r "$1" ]
+	then
+		echo "Error: Can't read configuration file"
+		exit 1
+	fi
+
 	# grep configuration from file
 	INTERVAL=`egrep '^INTERVAL=.*$' $1 | sed -e 's/INTERVAL=//g'`
 	FCTEMPS=`egrep '^FCTEMPS=.*$' $1 | sed -e 's/FCTEMPS=//g'`
