Detect improperly formatted FCTEMPS value (#2293).
git-svn-id: http://lm-sensors.org/svn/lm-sensors/branches/lm-sensors-3.0.0@5102 7894878c-1315-0410-8ee3-d5d059ff63e0

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -82,6 +82,13 @@ function LoadConfig {
 	let fcvcount=0
 	for fcv in $FCTEMPS
 	do
+		if ! echo $fcv | egrep -q '='
+		then
+			echo "Error in configuration file:"
+			echo "FCTEMPS value is improperly formatted"
+			exit 1
+		fi
+
 		AFCPWM[$fcvcount]=`echo $fcv |cut -d'=' -f1`
 		AFCTEMP[$fcvcount]=`echo $fcv |cut -d'=' -f2`
 		AFCFAN[$fcvcount]=`echo $FCFANS |sed -e 's/ /\n/g' |egrep "${AFCPWM[$fcvcount]}" |cut -d'=' -f2`
