Don't assume legacy references to i2c devices, instead explicitly check for them. This should help spot invalid configuration files.
git-svn-id: http://lm-sensors.org/svn/lm-sensors/trunk@5764 7894878c-1315-0410-8ee3-d5d059ff63e0

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -3,7 +3,7 @@
 # Simple script implementing a temperature dependent fan speed control
 # Supported Linux kernel versions: 2.6.5 and later
 #
-# Version 0.68
+# Version 0.69
 #
 # Usage: fancontrol [CONFIGFILE]
 #
@@ -166,8 +166,12 @@ then
 elif echo "${AFCPWM[0]}" | egrep -q '^hwmon[0-9]'
 then
 	DIR=/sys/class/hwmon
-else
+elif echo "${AFCPWM[0]}" | egrep -q '^[1-9]*[0-9]-[0-9abcdef]{4}'
+then
 	DIR=/sys/bus/i2c/devices
+else
+	echo "$0: Invalid path to sensors"
+	exit 1
 fi
 
 if [ ! -d $DIR ]
