Fix error message.
git-svn-id: http://lm-sensors.org/svn/lm-sensors/branches/lm-sensors-3.0.0@4692 7894878c-1315-0410-8ee3-d5d059ff63e0

diff --git a/prog/pwm/pwmconfig b/prog/pwm/pwmconfig
--- a/prog/pwm/pwmconfig
+++ b/prog/pwm/pwmconfig
@@ -190,7 +190,7 @@ do
 		pwmdisable $i
 		if [ $? -ne 0 ]
 		then
-			echo "Failed to set pwm$i to full speed" >&2
+			echo "Failed to set $i to full speed" >&2
 			echo "Something's wrong, check your fans!" >&2
 			exit 1
 		fi
